# Write an algorithm for getting dressed in the morning. Use enough detail to make sure you are fully ready to go.
print("My dad opens my door. I am still asleep. He says, Rubin.")
print("I get out of bed around 7:30am. I climb down from my wooden loft bed.")
print("I look for a pair of pants, a shirt, and underwear.")
print("My clothes in hand, I head to the bathroom to take a shower.")
print("When I get out of the shower, I dry myself off.")
print("Once I am all dry, I hang my towel back on the hook and put my clothes on.")
print("If I need to shave, I turn on my electric shaver and start shaving.")
print("I then put this hair cream in my hair to make my hair stay up.")
print("I take a little ball of it and rub it around in my hand.")
print("Then I take put it in my hair.")
print("I wash my hands to get the cream off and then I dry them with a towel.")
print("I then position my hair the way I want it.")
print("When I am finished doing my hair, I go back to my bedroom.")
print("I drop my pajamas on the floor.")
print("I open up my sock drawer and take out a pair of socks.")
print("I then finish packing up my bag and zip it closed.")
print("I head towards the door.")
print("I put my breakfast, which my dad has put into a little bag, into my backpack.")
print("I close my backpack.")
print("Then I put on my socks.")
print("I bend down and put on my shoes. I tie them if they're not tight enough after slipping them on.")
print("I put on a sweatshirt or a coat.")
print("I then open the door, walk out into the hallway, and let the door slam behind me.")
